[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://identity.netlify.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: blob: https:;
      connect-src 'self' blob: https://api.github.com https://gitgateway.netlify.com https://identity.netlify.com;
      frame-src 'self' https://identity.netlify.com;
    """
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
