[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' 'unsafe-inline' https://unpkg.com https://identity.netlify.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      connect-src 'self' https://api.github.com https://gitgateway.netlify.com https://identity.netlify.com;
      frame-src 'self' https://identity.netlify.com;
    """
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
