backend:
  name: git-gateway
  branch: main
  site_url: https://astro-demo3.netlify.app  # Thay your-site bằng URL thực
  commit_messages:
    create: "Create {{collection}} '{{slug}}'"
    update: "Update {{collection}} '{{slug}}'"
    delete: "Delete {{collection}} '{{slug}}'"
    uploadMedia: "Upload '{{path}}'"
    deleteMedia: "Delete '{{path}}'"

publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "/images"
display_url: https://astro-demo3.netlify.app

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Post"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: title
    fields:
      - { label: "Title", name: "title", widget: "string", pattern: ["^.{10,80}$", "Tiêu đề phải từ 10-80 ký tự"] }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "heading-two", "quote", "code", "bulleted-list"], editor_components: ["image", "code-block"] }
    editor:
      preview: true
      frame: false